# SPDX-FileCopyrightText: 2026 Eric Joldasov <bratishkaerik@landless-city.net>
#
# SPDX-License-Identifier: CC0-1.0

name: "Publish release to GitHub"

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack-source:
    name: Package source code
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Archive source
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          mkdir -p dist

          TIMESTAMP=$(git log -1 --format=%ct "${GITHUB_SHA}")
          export SOURCE_DATE_EPOCH="$TIMESTAMP"

          git -c tar.tgz.command="gzip -9 -n" archive --format=tar.gz \
            --mtime="@${TIMESTAMP}" \
            --prefix="ncdu-${VERSION}/" \
            --output="dist/ncdu-${VERSION}-src.tar.gz" \
            "${GITHUB_SHA}"

      - name: Upload source artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifact-source
          path: dist/
          retention-days: 1

  publish-github:
    name: Publish to GitHub Releases
    runs-on: ubuntu-latest
    needs: [ pack-source ]
    environment:
      name: github-releases
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Download clean build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: artifact-*
          path: dist/
          merge-multiple: true

      - name: Generate Artifact Attestation
        uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4.1.1
        with:
          subject-path: "dist/*"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_PRERELEASE: ${{
            contains(github.ref_name, 'rc') ||
            contains(github.ref_name, 'beta') ||
            contains(github.ref_name, 'alpha') ||
            contains(github.ref_name, 'dev') ||
            contains(github.ref_name, 'test') }}
        run: |
          set -euo pipefail
          shopt -s nullglob

          ARGS=("--draft")
          if [ "${IS_PRERELEASE}" = "true" ]; then
            ARGS+=("--prerelease")
          fi

          export LC_ALL=C.UTF-8
          mapfile -t FILES < <(printf "%s\n" dist/* | sort -r)

          git tag -l --format='%(contents:body)' "${GITHUB_REF_NAME}" > release_notes.md
          echo -e "## GitHub generated notes" >> release_notes.md

          gh release create "${GITHUB_REF_NAME}" "${FILES[@]}" \
            --title "Release ${GITHUB_REF_NAME}" \
            --notes-file release_notes.md \
            --generate-notes \
            "${ARGS[@]}"
