# SPDX-FileCopyrightText: 2026 Eric Joldasov <bratishkaerik@landless-city.net>
#
# SPDX-License-Identifier: CC0-1.0

name: "Publish release to GitHub"

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g., v0.1.0
      - v*

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack-source:
    name: Package source code
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Archive source
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          mkdir -p dist

          TIMESTAMP=$(git log -1 --format=%ct "${GITHUB_SHA}")
          export SOURCE_DATE_EPOCH="$TIMESTAMP"

          git -c tar.tgz.command="gzip -9 -n" archive --format=tar.gz \
            --mtime="@${TIMESTAMP}" \
            --prefix="ncdu-${VERSION}/" \
            --output="dist/ncdu-${VERSION}-src.tar.gz" \
            "${GITHUB_SHA}"

      - name: Upload source artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifact-source
          path: dist/
          retention-days: 1

  build-binaries:
    name: Build static binaries (${{ matrix.target }})
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - target: x86_64-linux-musl
            arch_suffix: linux-x86_64
            binutils: binutils

          - target: x86-linux-musl
            arch_suffix: linux-x86
            binutils: binutils-i686-linux-gnu
            strip_prefix: i686-linux-gnu-

          - target: aarch64-linux-musl
            arch_suffix: linux-aarch64
            binutils: binutils-aarch64-linux-gnu
            strip_prefix: aarch64-linux-gnu-

          - target: arm-linux-musleabi
            arch_suffix: linux-arm
            binutils: binutils-arm-linux-gnueabi
            strip_prefix: arm-linux-gnueabi-

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Zig
        id: setup-zig
        uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29 # v2
        with:
          use-cache: false

      - name: Build static binary
        run: |
          zig build -fno-sys=zstd -fno-sys=ncurses \
            -Dtarget=${{ matrix.target }} -Dcpu=baseline --release=fast -Dstrip -Dpie \
            --build-id=fast --prefix current-build

      - name: Install strip
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.binutils }}

      - name: Strip debug symbols
        run: ${{ matrix.strip_prefix }}strip -R .eh_frame -R .eh_frame_hdr current-build/bin/ncdu

      - name: Package binary
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          mkdir -p dist

          TIMESTAMP=$(git log -1 --format=%ct "${GITHUB_SHA}")
          export SOURCE_DATE_EPOCH="$TIMESTAMP"

          mv current-build/bin/ncdu current-build/ncdu
          chmod 755 current-build/ncdu

          tar --sort=name \
              --mtime="@${TIMESTAMP}" \
              --owner=0 --group=0 --numeric-owner \
              -cf "dist/ncdu-${VERSION}-${{ matrix.arch_suffix }}.tar" \
              -C current-build ncdu

          gzip -9 -n "dist/ncdu-${VERSION}-${{ matrix.arch_suffix }}.tar"

      - name: Upload binary artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artifact-${{ matrix.target }}
          path: dist/
          retention-days: 1
          if-no-files-found: error

  publish-github:
    name: Publish to GitHub Releases
    runs-on: ubuntu-latest
    needs: [ pack-source, build-binaries ]
    environment:
      name: github-releases
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Download clean build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          pattern: artifact-*
          path: dist/
          merge-multiple: true

      - name: Generate Artifact Attestation
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: "dist/*"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_PRERELEASE: ${{
            contains(github.ref_name, 'rc') ||
            contains(github.ref_name, 'beta') ||
            contains(github.ref_name, 'alpha') ||
            contains(github.ref_name, 'dev') ||
            contains(github.ref_name, 'test') }}
        run: |
          set -euo pipefail
          shopt -s nullglob

          ARGS=("--draft")
          if [ "${IS_PRERELEASE}" = "true" ]; then
            ARGS+=("--prerelease")
          fi

          export LC_ALL=C.UTF-8
          mapfile -t FILES < <(printf "%s\n" dist/* | sort -r)

          git tag -l --format='%(contents:body)' "${GITHUB_REF_NAME}" > release_notes.md
          echo -e "## GitHub generated notes" >> release_notes.md

          gh release create "${GITHUB_REF_NAME}" "${FILES[@]}" \
            --title "Release ${GITHUB_REF_NAME}" \
            --notes-file release_notes.md \
            --generate-notes \
            "${ARGS[@]}"
